apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-networking
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://github.com/example/onprem-platform.git
    path: platform/networking/manifests
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
