apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsphere-csi-node
  namespace: vmware-system-csi
  labels:
    app.kubernetes.io/name: vsphere-csi
    app.kubernetes.io/component: node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsphere-csi-node-role
  labels:
    app.kubernetes.io/name: vsphere-csi
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vsphere-csi-node-binding
  labels:
    app.kubernetes.io/name: vsphere-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vsphere-csi-node-role
subjects:
  - kind: ServiceAccount
    name: vsphere-csi-node
    namespace: vmware-system-csi
