apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: platform-critical-nightly
  namespace: velero
  labels:
    tier: platform
spec:
  schedule: "0 1 * * *" # 01:00 daily
  template:
    includedNamespaces:
      - platform-services   # Harbor and other platform services
      - argocd              # GitOps controllers and state
      - jenkins             # Jenkins controller PVCs
    snapshotVolumes: true
    defaultVolumesToFsBackup: true
    ttl: 168h
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: cluster-resources-daily
  namespace: velero
  labels:
    tier: platform
spec:
  schedule: "30 1 * * *" # 01:30 daily
  template:
    includeClusterResources: true
    snapshotVolumes: false
    ttl: 168h
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: weekly-restore-test-seed
  namespace: velero
  labels:
    tier: platform
spec:
  schedule: "0 3 * * 1" # 03:00 every Monday
  template:
    includedNamespaces:
      - platform-services
    snapshotVolumes: true
    defaultVolumesToFsBackup: true
    ttl: 48h
