apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsphere-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vsphere-cpi
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vsphere-cloud-controller-manager
  labels:
    app.kubernetes.io/name: vsphere-cpi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: vsphere-cloud-controller-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vsphere-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vsphere-cpi
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vsphere-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vsphere-cpi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vsphere-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: vsphere-cloud-controller-manager
    namespace: kube-system
